---
title: "(Informal) Statistics Research Induction"
author: "Emi Tanaka"
date: "Last Updated: `r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome to the world of research! It will be challenging but hopefully rewarding and give you a better idea of what research is all about. 

# Expectations

A common misconception perhaps is that a supervisor drives your research and explains what you do. *Research is different to course work*. There is no set pathway. The supervisor is there to provide you *guidance* but the person who drives the research and the work is *you*. In other words, it is expected that you are **proactive in your work**. 

The supervisor has experience and some understanding of your topic but will not necessary have the answer to all your questions (if they do then it's not research). As you get familiar with the topic, you should be able to explain to the supervisor about your topic (not the other way around). 

### Knowledge

I expect that you know `R` and some statistical modelling. Great if you know how to use R-Markdown and LaTeX; if not it is expected that you learn quickly. It is advisable to learn how to use [BibTeX](https://blog.mendeley.com/2011/10/25/howto-use-mendeley-to-create-citations-using-latex-and-bibtex/) for reference citations.

### Meeting

We would normally meet once a week for about an hour. Even if you do not have anything done or to report, we should meet. If you require to meet more then I prefer that we schedule this rather than you drop-in without schedule.

# Requirements

It is expected that you have your own computer with admin access. If you do not and would like one supplied to you, please contact our Computer Systems Manager, Paul Szabo, (paul.szabo@sydney.edu.au).

You should have:

* Latest [R](https://www.r-project.org/). 
* Latest [RStudio](https://www.rstudio.com/).
* [LaTeX](https://www.latex-project.org/get/).
* Get [Mendeley](https://www.mendeley.com) for reference management. 


You will need additional R packages including (but not limited to): `tidyverse` (or `ggplot2` and `dplyr`), `agridat`, `lme4`, and `rmarkdown`.


# Thesis Template

It is preferred that you use the template from  [here](https://github.com/emitanaka/SydneyThesisTemplate).

# Feedback

Any comments or questions, do contact Emi at dr.emi.tanaka@gmail.com.
